---
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
#    network_mode: host
    ports:
      - "32402:32400"
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=America/Boise
      - VERSION=docker
    volumes:
      - /plex-media/plex-config/:/config
      - /plex-media/:/plex-media
    restart: unless-stopped
  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - /plex-media/plex-config/tautilli/:/config
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=America/Boise
    ports:
      - 8183:8181
  filterapp:
    image: madmandrew/filterapp:latest
    container_name: filterapp
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1001
      - REACT_APP_SERVER_URL=http://192.168.50.38:8000/
    volumes:
      - /plex-media:/plex-media
    ports:
      - 8000:8000
